# Generated by Django 5.2 on 2025-05-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('registration_date', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('residential_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('full_legal_name__isnull', False)), fields=('full_legal_name',), name='unique_owner_name')],
            },
        ),
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('gun_model', models.CharField(max_length=255)),
                ('gun_type', models.CharField(choices=[('handgun', 'Handgun'), ('rifle', 'Rifle'), ('shotgun', 'Shotgun'), ('submachine', 'Submachine Gun'), ('other', 'Other')], max_length=20)),
                ('ammunition_type', models.CharField(max_length=100)),
                ('firearm_status', models.CharField(choices=[('deposit', 'Deposit'), ('confiscated', 'Confiscated'), ('surrendered', 'Surrendered'), ('abandoned', 'Abandoned')], max_length=20)),
                ('date_of_collection', models.DateField()),
                ('registration_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firearms', to='api.owner')),
            ],
        ),
    ]
